name: Update repository
on:
  schedule:
    - cron: '20 20 * * *'
      job: add_empty_file
    - cron: '20 8 * * *'
      job: remove_empty_file
  workflow_dispatch:
jobs:
  add_empty_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Add empty file
        run: |
          touch IMG/sync.txt
          git add IMG/sync.txt
          git config user.name "anonymous"
          git config user.email "gmailqq163@hotmail.com"
          git commit -m "sync1"
          git push origin main
  remove_empty_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Remove empty file
        run: |
          git rm IMG/sync.txt
          git config user.name "anonymous"
          git config user.email "gmailqq163@hotmail.com"
          git commit -m "sync2"
          git push origin main
